// This is a Base64 encoded GLB file of a simple arm model.
// In a real application, this would be generated by the AI model.
export const MOCK_ARM_MODEL_URI = 'data:model/gltf-binary;base64,Z2xURgIAA...'; // Truncated for brevity. A full valid data URI would be used here.
// For a working demo, you would replace the "..." with a full Base64 string of a GLB model.
// Due to payload size limits, a full model is not included here.
// You can find free GLB models online and convert them to a Base64 data URI.
// A placeholder cube will be used in the viewer instead.
